name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permisos a gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Test
        run: ./gradlew test --tests proyecto.runner.runner

      - name: Guardar reporte Cucumber
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: app/target/cucumber-reports.html

      - name: Subir resultados Cucumber a Xray
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
        run: |
          TOKEN=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
            -H 'Content-Type: application/json' \
            -d '{"client_id": "'$XRAY_CLIENT_ID'", "client_secret": "'$XRAY_CLIENT_SECRET'"}' | tr -d '"')
          curl -H "Authorization: Bearer $TOKEN" \
            -F "file=@app/target/cucumber.json" \
            "https://xray.cloud.getxray.app/api/v2/import/execution/cucumber?projectKey=DEMO"

      - name: Guardar resultados JUnit
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: app/build/test-results/**/*.xml

      - name: Instalar Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar chromedriver
        run: |
          sudo apt-get install -yqq unzip
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
